using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Euler.Models
{
    public class EvenFibonacci : EulerProblem
    {
        public EvenFibonacci()
        {
            Name = "2: Even Fibonacci numbers";
            Description = $"Each new term in the Fibonacci sequence is generated by adding the previous two terms.{Environment.NewLine} " +
                $"By starting with 1 and 2, the first 10 terms will be:{Environment.NewLine} " +
                $"1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...{Environment.NewLine}" +
                $"By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";
        }

        public override void SolveProblem()
        {
            List<int> even = new List<int>();
            Print("Start:");
            int y1 = 1;
            int y2 = 2;
            even.Add(y2);
            int next = y1 + y2;
            y1 = y2;
            y2 = next;
            while ((y1 + y2) < 4000000)
            {
                for (int i = 1; i <= 3; i++)
                {
                    next = y1 + y2;
                    y1 = y2;
                    y2 = next;
                }
                even.Add(y1);
            }

            Print($"Result: {even.Sum()}");
            Print($"{string.Join(" ",even)}");
        }
    }
}
